apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: innovatech-ventas-hpa       # Nombre único para el autoescalador de Ventas
  namespace: innovatech
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: innovatech-ventas-deployment # Apunta exactamente a tu Deployment de Ventas
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70