apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: innovatech-despacho-hpa     # Nombre único para el autoescalador de Despachos
  namespace: innovatech
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: innovatech-despacho-deployment # Apunta exactamente a tu Deployment de Despachos
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70