apiVersion: v1
kind: Service
metadata:
  name: innovatech-despacho-service 
  namespace: innovatech
spec:
  selector:
    app: innovatech-despacho        
  ports:
    - port: 80                      
      targetPort: 8081              
  type: ClusterIP