apiVersion: apps/v1
kind: Deployment
metadata:
  name: innovatech-despacho-deployment
  namespace: innovatech
spec:
  replicas: 2                     # Mantiene 2 pods corriendo para alta disponibilidad
  selector:
    matchLabels:
      app: innovatech-despacho
  template:
    metadata:
      labels:
        app: innovatech-despacho
    spec:
      containers:
        - name: innovatech-despacho
          image: 884762245823.dkr.ecr.us-east-1.amazonaws.com/innovatech-despachos:eks-v1
          ports:
            - containerPort: 8081  # Puerto configurado para Despachos
          env:
            # Sobreescribimos las variables estándar de Spring Boot para asegurar la conexión a tu RDS
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://innovatech-db.cdyvr8j8ttyt.us-east-1.rds.amazonaws.com:3306/app_db?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true"
            - name: SPRING_DATASOURCE_USERNAME
              value: "app_user"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "app_password"

          # Recursos asignados para que funcione el Metrics Server (HPA)
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          # VALIDACIONES DE SALUD (Ajustadas a tu ruta de Swagger en puerto 8081)
          readinessProbe:
            httpGet:
              path: /swagger-ui.html
              port: 8081
            initialDelaySeconds: 20
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /swagger-ui.html
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10